# Generated by Django 5.0.4 on 2024-04-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='events/'),
            preserve_default=False,
        ),
    ]
