# Generated by Django 5.0.4 on 2024-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='phone_number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
