# Generated by Django 5.0.4 on 2024-04-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_relative_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('event', 'relative')},
        ),
    ]
